conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path, include
)

from . import views

urlpatterns = [
    path('',
         views.HomeView.as_view(), name='home'),

    path('chatbot/',
         include('chatbot.urls', namespace='chatbot')),

    path('golf/',
         include('golf.urls', namespace='golf')),

    path('liff/',
         include('liff.urls', namespace='liff')),

    path('console/',
         include('console.urls', namespace='console')),

    path('member/',
         include('member.urls', namespace='member')),

    path('accounts/',
         include('allauth.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'conf.views.handler404'
handler403 = 'conf.views.handler403'
handler500 = 'conf.views.handler500'

console/urls.py
from django.urls import path

from . import views

app_name = 'console'

urlpatterns = [
    path('<slug:slug>/',
         views.HomeView.as_view(), name='home'),

    path('<slug:slug>/orders/',
         views.GolfBookingOrderListView.as_view(), name='golf-booking-order-list'),

    path('<slug:slug>/orders/<uuid:uuid>/',
         views.GolfBookingOrderDetailView.as_view(), name='golf-booking-order-detail'),

    path('<slug:slug>/line-users/',
         views.LineUserListView.as_view(), name='line-user-list'),

    path('<slug:slug>/line-users/<str:line_user_id>/',
         views.LineUserDetailView.as_view(), name='line-user-detail'),

    path('<slug:slug>/facebook-users/',
         views.FacebookUserListView.as_view(), name='facebook-user-list'),

    path('<slug:slug>/facebook-users/<str:facebook_user_id>/',
         views.FacebookUserDetailView.as_view(), name='facebook-user-detail'),

    path('<slug:slug>/settings/golf-club/',
         views.GolfClubUpdateView.as_view(), name='golf-club-update'),

    path('<slug:slug>/settings/rates/',
         views.GreenFeeListView.as_view(), name='green-fee-list'),

    path('<slug:slug>/settings/holidays/',
         views.HolidayListView.as_view(), name='holiday-list'),

    path('<slug:slug>/settings/seasons/',
         views.SeasonListView.as_view(), name='season-list'),

    path('<slug:slug>/settings/timeslots/',
         views.TimeslotListView.as_view(), name='timeslot-list'),

    path('<slug:slug>/settings/staffs/',
         views.StaffListView.as_view(), name='staff-list'),
]

golf/models.py
import json
import uuid
from decimal import Decimal
from pathlib import Path

from django.conf import settings
from django.core.files.storage import default_storage
from django.db import models
from django.template.defaultfilters import time
from django.utils import translation
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils import models as model_utils_models


def golf_club_upload_directory_path(instance, filename):
    return f"golf/{instance.slug}/{uuid.uuid4()}.{filename.split('.')[-1]}"


def promotion_upload_directory_path(instance, filename):
    return f"golf/{instance.slug}/promotion/{uuid.uuid4()}.{filename.split('.')[-1]}"


def coupon_upload_directory_path(instance, filename):
    return f"golf/{instance.slug}/coupon/{uuid.uuid4()}.{filename.split('.')[-1]}"


def caddie_upload_directory_path(instance, filename):
    return f"golf/{instance.slug}/caddie/{uuid.uuid4()}.{filename.split('.')[-1]}"


class Holiday(model_utils_models.TimeStampedModel):
    title = models.CharField(
        verbose_name=_('Holiday name'),
        max_length=255,
    )

    holiday = models.DateField(
        verbose_name=_('Holiday day'),
        db_index=True,
        unique=True,
    )

    class Meta:
        verbose_name = _('Holiday')
        verbose_name_plural = _('Holidays')

    def __str__(self):
        return f'{self.title} {self.holiday}'


class Area(model_utils_models.TimeStampedModel):
    title_english = models.CharField(
        verbose_name=_('Area english name'),
        max_length=255,
    )

    title_thai = models.CharField(
        verbose_name=_('Area Thai name'),
        max_length=255,
    )

    title_korean = models.CharField(
        verbose_name=_('Area Korean name'),
        max_length=255,
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        help_text=_('A short label containing only letters, numbers, underscores or hyphens for URL'),
        max_length=255,
        db_index=True,
        unique=True,
        allow_unicode=True,
    )

    position = models.IntegerField(
        verbose_name=_('Position'),
        default=0,
        db_index=True,
    )

    class Meta:
        verbose_name = _('Area')
        verbose_name_plural = _('Areas')

    def __str__(self):
        return f'{self.title_english}'


class Province(model_utils_models.TimeStampedModel):
    title_english = models.CharField(
        verbose_name=_('Province English name'),
        max_length=255,
    )

    title_thai = models.CharField(
        verbose_name=_('Province Thai name'),
        max_length=255,
    )

    title_korean = models.CharField(
        verbose_name=_('Province Korean name'),
        max_length=255,
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        help_text=_('A short label containing only letters, numbers, underscores or hyphens for URL'),
        max_length=255,
        db_index=True,
        unique=True,
        allow_unicode=True,
    )

    area = models.ForeignKey(
        'golf.Area',
        verbose_name=_('Location area'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    position = models.IntegerField(
        verbose_name=_('Position'),
        default=0,
        db_index=True,
    )

    class Meta:
        verbose_name = _('Province')
        verbose_name_plural = _('Provinces')

    def __str__(self):
        return f'{self.title_english}'


class District(model_utils_models.TimeStampedModel):
    title_english = models.CharField(
        verbose_name=_('District English name'),
        max_length=255,
    )

    title_thai = models.CharField(
        verbose_name=_('District Thai name'),
        max_length=255,
    )

    title_korean = models.CharField(
        verbose_name=_('District Korean name'),
        max_length=255,
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        help_text=_('A short label containing only letters, numbers, underscores or hyphens for URL'),
        max_length=255,
        db_index=True,
        unique=True,
        allow_unicode=True,
    )

    province = models.ForeignKey(
        'golf.Province',
        verbose_name=_('Province'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    position = models.IntegerField(
        verbose_name=_('Position'),
        default=0,
        db_index=True,
    )

    class Meta:
        verbose_name = _('District')
        verbose_name_plural = _('Districts')

    def __str__(self):
        return f'{self.title_english}'


class GolfClub(model_utils_models.TimeStampedModel):
    HOLE_CHOICES = Choices(
        (0, 'eighteen', _('18 Holes')),
        (1, 'nine', _('9 Holes')),
        (2, 'twentyseven', _('27 Holes')),
        (3, 'thirtysix', _('36 Holes')),
    )

    WORKING_CHOICES = Choices(
        (0, 'open', _('Course open')),
        (1, 'closed', _('Course closed')),
        (2, 'suspended', _('Suspended')),
    )

    CADDIE_COMPULSORY_CHOICES = Choices(
        (0, 'optional', _('Optional')),
        (1, 'compulsory', _('Compulsory')),
    )

    CART_COMPULSORY_CHOICES = Choices(
        (0, 'optional', _('Optional')),
        (1, 'compulsory', _('Compulsory')),
        (2, 'compulsory2', _('Compulsory 2 player+')),
        (3, 'compulsory3', _('Compulsory 3 player+')),
        (4, 'compulsory4', _('Compulsory 4 player+')),
        (5, 'compulsory5', _('Compulsory 5 player+')),
        (6, 'compulsory6', _('Compulsory 6 player+')),
    )

    title_english = models.CharField(
        verbose_name=_('Golf club English name'),
        max_length=255,
        db_index=True,
    )

    title_thai = models.CharField(
        verbose_name=_('Golf club Thai name'),
        max_length=255,
        db_index=True,
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        help_text=_('A short label containing only letters, numbers, underscores or hyphens for URL'),
        max_length=255,
        db_index=True,
        unique=True,
        allow_unicode=True,
    )

    line_bot_channel_access_token = models.CharField(
        verbose_name=_('LINE bot channel access token'),
        max_length=255,
        blank=True,
        null=True,
    )

    line_bot_channel_secret = models.CharField(
        verbose_name=_('LINE bot channel secret'),
        max_length=64,
        blank=True,
        null=True,
    )

    line_notify_access_token = models.CharField(
        verbose_name=_('LINE notify access token'),
        max_length=64,
        blank=True,
        null=True,
    )

    info_flex_message = models.JSONField(
        verbose_name=_('Course info flex message'),
        blank=True,
        null=True,
    )

    order_flex_message = models.JSONField(
        verbose_name=_('Order flex message'),
        blank=True,
        null=True,
    )

    no_order_flex_message = models.JSONField(
        verbose_name=_('No order flex message'),
        blank=True,
        null=True,
    )

    customer_group = models.ForeignKey(
        'golf.CustomerGroup',
        verbose_name=_('Default customer group'),
        null=True,
        blank=True,
        editable=True,
        db_index=True,
        on_delete=models.SET_NULL,
    )

    business_hour_start = models.TimeField(
        verbose_name=_('Business hour start'),
    )

    business_hour_end = models.TimeField(
        verbose_name=_('Business hour end'),
    )

    phone = models.CharField(
        verbose_name=_('Phone number'),
        max_length=32,
        blank=True,
        null=True,
    )

    email = models.EmailField(
        verbose_name=_('Email address'),
        max_length=255,
        blank=True,
        null=True,
    )

    fax = models.CharField(
        verbose_name=_('Fax number'),
        max_length=16,
        blank=True,
        null=True,
    )

    website = models.URLField(
        verbose_name=_('Website'),
        max_length=255,
        blank=True,
        null=True,
    )

    district = models.ForeignKey(
        'golf.District',
        verbose_name=_('District'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    address = models.CharField(
        verbose_name=_('Golf club address'),
        max_length=255,
        blank=True,
        null=True,
    )

    latitude = models.DecimalField(
        verbose_name=_('Latitude'),
        max_digits=10,
        decimal_places=7,
        default=0,
    )

    longitude = models.DecimalField(
        verbose_name=_('Longitude'),
        max_digits=10,
        decimal_places=7,
        default=0,
    )

    hole = models.IntegerField(
        verbose_name=_('No. of holes'),
        choices=HOLE_CHOICES,
        default=HOLE_CHOICES.eighteen,
        db_index=True,
    )

    min_pax = models.IntegerField(
        verbose_name=_('Min PAX'),
        default=1,
    )

    max_pax = models.IntegerField(
        verbose_name=_('Max PAX'),
        default=4,
    )

    weekdays_min_in_advance = models.IntegerField(
        verbose_name=_('Weekdays minimum in advance'),
        default=1,
        db_index=True,
    )

    weekdays_max_in_advance = models.IntegerField(
        verbose_name=_('Weekdays maximum in advance'),
        default=30,
        db_index=True,
    )

    weekend_min_in_advance = models.IntegerField(
        verbose_name=_('Weekend minimum in advance'),
        default=1,
        db_index=True,
    )

    weekend_max_in_advance = models.IntegerField(
        verbose_name=_('Weekend maximum in advance'),
        default=7,
        db_index=True,
    )

    weekend_booking_on_monday = models.BooleanField(
        verbose_name=_('Weekend booking on Monday'),
        default=False,
    )

    multiple_booking_orders = models.PositiveIntegerField(
        verbose_name=_('Multiple booking orders'),
        default=1,
    )

    caddie_compulsory = models.IntegerField(
        verbose_name=_('Caddie compulsory'),
        choices=CADDIE_COMPULSORY_CHOICES,

console/forms.py
from django import forms
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from golf import models as golf_models


class ConfirmForm(forms.Form):
    round_time = forms.TimeField(required=True)

    def clean_round_time(self):
        data = self.cleaned_data['round_time']

        if data < timezone.datetime.strptime('06:00', '%H:%M').time() \
                or data > timezone.datetime.strptime('20:00', '%H:%M').time():
            raise forms.ValidationError(_('Invalid round time'))

        return data


class OfferForm(forms.Form):
    tee_off_times = forms.TimeField(widget=forms.HiddenInput(), required=False)

    def clean_tee_off_times(self):
        tee_off_times = list(filter(None, self.data.getlist('tee_off_times')))

        if len(tee_off_times) == 0:
            raise forms.ValidationError(_('No round time is offered.'))

        return tee_off_times


class RejectForm(forms.Form):
    pass


class OrderSearchForm(forms.Form):
    search = forms.ChoiceField(
        choices=(
            ('round_date', _('Round Date'),),
            ('customer_name', _('Customer'),),
        ),
        required=False,
    )

    keyword = forms.TimeField(
        label=_('Keyword'),
        required=False,
        widget=forms.TimeInput(
            attrs={
                'class': 'input is-fullwidth',
                'placeholder': _('HH:MM'),
            }
        ),
    )

    order_status = forms.ChoiceField(
        choices=(
            ('', _('Order Status'),),
            ('open', _('Open'),),
            ('offered', _('Offered'),),
            ('accepted', _('Accepted'),),
            ('confirmed', _('Confirmed'),),
            ('closed', _('Closed'),),
        ),
        required=False,
    )

    payment_status = forms.ChoiceField(
        choices=(
            ('', _('Payment Status'),),
            ('unpaid', _('Not paid'),),
            ('paid', _('Paid'),),
            ('refund_requests', _('Refund requests'),),
            ('refunded', _('Refunded'),),
        ),
        required=False,
    )

    sort = forms.ChoiceField(
        choices=(
            ('booking_date', _('Booking Date'),),
            ('round_date', _('Round Date'),),
        ),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        search = kwargs.pop('search', 'round_date')
        keyword = kwargs.pop('keyword', '')
        order_status = kwargs.pop('order_status', '')
        payment_status = kwargs.pop('payment_status', '')
        sort = kwargs.pop('sort', 'booking_date')

        super(OrderSearchForm, self).__init__(*args, **kwargs)

        self.fields['search'].initial = search
        self.fields['keyword'].initial = keyword
        self.fields['order_status'].initial = order_status
        self.fields['payment_status'].initial = payment_status
        self.fields['sort'].initial = sort


class GolfClubForm(forms.ModelForm):
    class Meta:
        model = golf_models.GolfClub
        fields = ('slug',)


class GreenFeeSearchForm(forms.Form):
    seasons = forms.ModelChoiceField(
        queryset=None,
        empty_label=_('Seasons'),
        required=False,
    )

    day_of_week = forms.ChoiceField(
        choices=[('', _('Day of Week'))] + golf_models.Timeslot.DAY_CHOICES,
        required=False,
    )

    timeslots = forms.ModelChoiceField(
        queryset=None,
        empty_label=_('Timeslots'),
        required=False,
    )

    customer_groups = forms.ModelChoiceField(
        queryset=None,
        empty_label=_('Customer Groups'),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        slug = kwargs.pop('slug', '')
        seasons = kwargs.pop('seasons', '')
        day_of_week = kwargs.pop('day_of_week', '')
        timeslots = kwargs.pop('timeslots', '')
        customer_groups = kwargs.pop('customer_groups', '')

        super(GreenFeeSearchForm, self).__init__(*args, **kwargs)

        if slug:
            self.fields['seasons'].queryset = golf_models.Season.objects \
                .filter(golf_club__slug=slug) \
                .order_by('-season_end')

            self.fields['seasons'].label_from_instance = lambda obj: \
                f'{obj.season_start} {obj.season_end}'

            self.fields['timeslots'].queryset = golf_models.Timeslot.objects \
                .filter(golf_club__slug=slug) \
                .order_by('day_of_week', 'slot_start')

            self.fields['timeslots'].label_from_instance = lambda obj: \
                f'{obj.slot_start:%H:%M} {obj.slot_end:%H:%M} ({obj.title_english})'

            self.fields['customer_groups'].queryset = golf_models.CustomerGroup.objects \
                .filter(golf_club__slug=slug) \
                .order_by('position')

            self.fields['customer_groups'].label_from_instance = lambda obj: \
                f'{obj.title_english}'

        self.fields['seasons'].initial = seasons
        self.fields['day_of_week'].initial = day_of_week
        self.fields['timeslots'].initial = timeslots
        self.fields['customer_groups'].initial = customer_groups

console/templates/console/_left_sidebar_booking.html
{% load static i18n %}

<li class="submenu-heading">
    {% trans 'Booking' %}
    {% if left_sidebar_close_button %}
    <a class="is-pulled-right" id="left-sidebar-close">
        <i class="fas fa-times"></i>
    </a>
    {% endif %}
</li>
<li>
    <ul>
        <li class="submenu-item">
            <a href="{% url 'console:golf-booking-order-list' slug %}" class="is-capitalized">
                {% trans 'All booking list' %}
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:golf-booking-order-list' slug %}?order_status=open">
                <span class="tag status-open">{% trans 'Open' %}</span>
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:golf-booking-order-list' slug %}?order_status=accepted">
                <span class="tag status-accepted">{% trans 'Accepted' %}</span>
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:golf-booking-order-list' slug %}?payment_status=unpaid">
                <span class="tag status-unpaid is-capitalized">{% trans 'Not paid' %}</span>
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:golf-booking-order-list' slug %}?payment_status=refund_requests">
                <span class="tag status-refund-requests is-capitalized">{% trans 'Refund requests' %}</span>
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:golf-booking-order-list' slug %}?day=today">
                {% trans 'Today' %}
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:golf-booking-order-list' slug %}?day=tomorrow">
                {% trans 'Tomorrow' %}
            </a>
        </li>
    </ul>
</li>
<li class="submenu-heading">{% trans 'Customers' %}</li>
<li>
    <ul>
        <li class="submenu-item">
            <a href="{% url 'console:line-user-list' slug %}" class="is-capitalized">
                {% trans 'LINE users' %}
            </a>
        <li class="is-hidden">
            <a href="#" class="is-capitalized">
                {% trans 'Facebook users' %}
            </a>
        </li>
        <li class="submenu-item">
            <a>{% trans 'Customer groups' %}</a>
        </li>
    </ul>
</li>
<li class="submenu-heading">{% trans 'Marketing' %}</li>
<li>
    <ul>
        <li class="submenu-item">
            <a>{% trans 'Promotions' %}</a>
        </li>
        <li class="submenu-item">
            <a>{% trans 'Coupons' %}</a>
        </li>
        <li class="submenu-item">
            <a class="is-capitalized">{% trans 'Hot deals' %}</a>
        </li>
    </ul>
</li>
<li class="submenu-heading">{% trans 'Report' %}</li>
<li>
    <ul>
        <li class="submenu-item">
            <a class="is-capitalized">{% trans 'Daily sales' %}</a>
        </li>
        <li class="submenu-item">
            <a class="is-capitalized">{% trans 'Monthly sales' %}</a>
        </li>
        <li class="submenu-item">
            <a class="is-capitalized">{% trans 'Best promotions' %}</a>
        </li>
        <li class="submenu-item">
            <a class="is-capitalized"> {% trans 'Best customers' %} </a>
        </li>
        <li class="submenu-item">
            <a class="is-capitalized">{% trans 'Sales by customer groups' %}</a>
        </li>
        <li class="submenu-item">
            <a class="is-capitalized">{% trans 'Sales by payment' %}</a>
        </li>
    </ul>
</li>

console/templates/console/_right_sidebar_club_settings.html
{% load static i18n %}

<li class="submenu-heading">
    {% trans 'Settings' %}
    {% if right_sidebar_close_button %}
    <a class="is-pulled-right" id="right-sidebar-close">
        <i class="fas fa-times"></i>
    </a>
    {% endif %}
</li>
<li>
    <ul>
        <li class="submenu-item">
            <a href="{% url 'console:golf-club-update' slug %}" class="is-capitalized">
                {% trans 'Golf club' %}
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:green-fee-list' slug %}" class="is-capitalized">
                {% trans 'Green fee' %}
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:holiday-list' slug %}">
                {% trans 'Holidays' %}
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:season-list' slug %}">
                {% trans 'Seasons' %}
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:timeslot-list' slug %}">
                {% trans 'Timeslots' %}
            </a>
        </li>
        <li class="submenu-item">
            <a href="{% url 'console:staff-list' slug %}">
                {% trans 'Staffs' %}
            </a>
        </li>
    </ul>
</li>

console/templates/console/golf_booking_order_list.html
{% extends './console_base.html' %}

{% load static i18n humanize %}
{% load console_filters %}

{% block title %}
with-thai::{% trans 'Golf booking order list' %}
{% endblock %}

{% block content %}
<div>
    <div class="card">
        <header class="card-header">
            <div class="card-header-title is-capitalized">{% trans 'All booking list' %}</div>
        </header>
        <div class="card-content">
            <div class="content">
                {% include './_order_search_box.html' with form=form %}

                {% for order in orders %}
                <div class="columns is-multiline is-mobile is-vcentered mobile-list-item">
                    <div class="column is-hidden-tablet is-4-mobile">
                        <a href="{% url 'console:golf-booking-order-detail' slug order.order_no %}?{{ q }}">
                            {{ order.order_no|truncatechars:9 }}
                        </a>
                    </div>
                    <div class="column is-2-tablet is-8-mobile">
                        <a href="{% url 'console:golf-booking-order-detail' slug order.order_no %}?{{ q }}">
                            <div class="tags has-addons is-hidden-tablet status-tags is-capitalized">
                                {% if order.order_status == order.ORDER_STATUS_CHOICES.open %}
                                <span class="tag status-open">{{ order.get_order_status_display }}</span>
                                {% elif order.order_status == order.ORDER_STATUS_CHOICES.offered %}
                                <span class="tag status-offered">{{ order.get_order_status_display }}</span>
                                {% elif order.order_status == order.ORDER_STATUS_CHOICES.accepted %}
                                <span class="tag status-accepted">{{ order.get_order_status_display }}</span>
                                {% elif order.order_status == order.ORDER_STATUS_CHOICES.confirmed %}
                                <span class="tag status-confirmed">{{ order.get_order_status_display }}</span>
                                {% elif order.order_status == order.ORDER_STATUS_CHOICES.closed %}
                                <span class="tag status-closed">{{ order.get_order_status_display }}</span>
                                {% endif %}

                                {% if order.payment_status == order.PAYMENT_STATUS_CHOICES.unpaid %}
                                <span class="tag status-unpaid">{{ order.get_payment_status_display }}</span>
                                {% elif order.payment_status == order.PAYMENT_STATUS_CHOICES.paid %}
                                <span class="tag status-paid">{{ order.get_payment_status_display }}</span>
                                {% elif order.payment_status == order.PAYMENT_STATUS_CHOICES.refund_requests %}
                                <span class="tag status-refund-requests">{{ order.get_payment_status_display }}</span>
                                {% elif order.payment_status == order.PAYMENT_STATUS_CHOICES.refunded %}
                                <span class="tag status-refunded">{{ order.get_payment_status_display }}</span>
                                {% endif %}
                            </div>
                            <div class="is-hidden-mobile is-capitalized">
                                <div class="field is-grouped">
                                    <div class="control">
                                        {% if order.order_status == order.ORDER_STATUS_CHOICES.open %}
                                        <span class="tag status-open">{{ order.get_order_status_display }}</span>
                                        {% elif order.order_status == order.ORDER_STATUS_CHOICES.offered %}
                                        <span class="tag status-offered">{{ order.get_order_status_display }}</span>
                                        {% elif order.order_status == order.ORDER_STATUS_CHOICES.accepted %}
                                        <span class="tag status-accepted">{{ order.get_order_status_display }}</span>
                                        {% elif order.order_status == order.ORDER_STATUS_CHOICES.confirmed %}
                                        <span class="tag status-confirmed">{{ order.get_order_status_display }}</span>
                                        {% elif order.order_status == order.ORDER_STATUS_CHOICES.closed %}
                                        <span class="tag status-closed">{{ order.get_order_status_display }}</span>
                                        {% endif %}
                                    </div>
                                    <div class="control">
                                        {% if order.payment_status == order.PAYMENT_STATUS_CHOICES.unpaid %}
                                        <span class="tag status-unpaid">{{ order.get_payment_status_display }}</span>
                                        {% elif order.payment_status == order.PAYMENT_STATUS_CHOICES.paid %}
                                        <span class="tag status-paid">{{ order.get_payment_status_display }}</span>
                                        {% elif order.payment_status == order.PAYMENT_STATUS_CHOICES.refund_requests %}
                                        <span class="tag status-refund-requests">{{ order.get_payment_status_display }}</span>
                                        {% elif order.payment_status == order.PAYMENT_STATUS_CHOICES.refunded %}
                                        <span class="tag status-refunded">{{ order.get_payment_status_display }}</span>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="column is-2-tablet is-12-mobile has-text-weight-bold has-text-right is-family-monospace">
                        {{ order.round_date|date:'Y-m-d' }}
                        {{ order.round_time|date:'H:i' }}
                    </div>
                    <div class="column is-1-tablet is-hidden-mobile has-text-right is-family-monospace">
                        {{ order.pax }} PAX
                    </div>
                    <div class="column is-1-tablet is-hidden-mobile has-text-right is-family-monospace">
                        {{ order.cart }} CART
                    </div>
                    <div class="column is-2-tablet is-12-mobile has-text-right has-text-weight-bold is-family-monospace">
                        {{ order.total_selling_price|floatformat:0|intcomma }} THB
                        <span class="is-hidden-tablet">
                            / <i class="fas fa-users fa-fw"></i>
                            {{ order.pax }} PAX
                            / <i class="fas fa-truck-pickup fa-fw"></i>
                            {{ order.cart }} CART
                        </span>
                    </div>
                    <div class="column is-4-tablet is-12-mobile has-text-right-mobile">
                        {% if order.customer_group.title_english %}
                        <span class="tag status-customer-{{ order.customer_group.id|modulo:5 }} is-hidden-mobile">
                            {{ order.customer_group.title_english }}
                        </span>
                        {% endif %}
                        <a href="{% url 'console:golf-booking-order-detail' slug order.order_no %}?{{ q }}">
                            {{ order.fullname }}
                        </a>
                        {% if order.customer_group.title_english %}
                        <span class="tag status-customer-{{ order.customer_group.id|modulo:5 }} is-hidden-tablet">
                            {{ order.customer_group.title_english }}
                        </span>
                        {% endif %}
                    </div>
                </div>
                {% empty %}
                <div class="columns">
                    <div class="column has-text-centered has-text-weight-bold has-text-danger-dark">
                        {% trans 'Golf booking order is not found.' %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="page-pagination">
    {% include './_pagination.html' with page_obj=page_obj page_range=page_range q=q_popped %}
</div>
{% endblock %}

{% block javascript %}
{{ block.super }}
<script src="{% static 'js/console/order-list.js' %}"></script>
{% endblock %}

console/templates/console/home.html
{% extends './console_base.html' %}

{% load i18n static humanize %}

{% block title %}
with-thai::Admin Console
{% endblock %}

{% block content %}
<p>dashboard</p>
{% endblock %}